project:
  type: website

website:
  title: "data-limite"
  description: "open data, data science, visualization by MJ Duarte Rosa"
  favicon: map_arvores_app.png
  image: map_arvores_app.png
  repo-url: https://github.com/mjduarterosa/quarto-blog
  open-graph: true
  site-url: https://github.com/mjduarterosa/quarto-blog
  navbar:
    search: true
    right:
      - text: "Blog"
        file: index.qmd
      - text: "Resources"
        file: static/resources/resources.qmd
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/mjduarterosa
      - icon: rss
        href: index.xml
      - icon: cup-straw
        href: https://drinksbytom.com
format:
  html:
    author: "MJ Duarte Rosa"
    comments:
      utterances:
        repo: mjduarterosa/quarto-blog
    toc: true
    toc-location: "left"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    mainfont: "Lato"
    monofont: "Fira Mono"
    footnotes-hover: true
    fontsize: 1em
    theme: my-litera.scss
    css: styles.css
